name: Build cub3D

on:
  push:
    branches: [ "main", "alex", "clement" ]
  pull_request:
    branches: [ "main", "alex", "clement" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libxext-dev libbsd-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev python3-pip
          sudo pip3 install norminette

      - name: Run norminette
        run: |
          norminette src/ include/ libft/

      - name: Compile cub3D
        run: make

      - name: Compile bonus version
        run: make bonus

      - name: Clean build
        run: make fclean
